name = "tuchuang"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "public"
entry-point = "workers-site"

[vars]
GITHUB_OWNER = "Aiky156"
GITHUB_REPO = "tuchuangkangku"

[build]
command = "npm run build"