name = "image-hosting-service"
compatibility_date = "2024-01-01"

[vars]
GITHUB_OWNER = "Aiky156"
GITHUB_REPO = "tuchuangkangku"

[build]
command = ""

[functions]
bundle_path = "/functions"
include_files = ["node_modules/**/*"] 